services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: samba-admin-backend
    env_file:
      - docker/backend.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/backend/app/data
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: samba-admin-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
